### ISSUE TITLE
Endwalker cd changes

### ISSUE THREAD

**Issue by 542673** [Aho-Senpai/Aho-Triggers#10]
Latest patch changed WHM's Assize and DRG's Life surge cooldown from 45s to 40s but the triggers are outdated

**Comment by Aho-Senpai** [comment]
are those the only changes?

**Comment by Aho-Senpai** [comment]
latest commit fixes that

https://github.com/Aho-Senpai/Aho-Triggers/commit/d464236e8e646b7c9e68b8eef2db8c913b2625de

**Comment by 542673** [comment]
I do believe those were the only cooldown changes yes, rest was just potency adjustments
